[build]
builder = "DOCKERFILE"
target = "production"

[deploy]
startCommand = "pip install -r requirements.txt && python -m gunicorn app:app --bind 0.0.0.0:$PORT --workers 2 --timeout 120"
restartPolicyType = "ON_FAILURE" 