[build]
builder = "nixpacks"

[deploy]
startCommand = "pip install -r requirements.txt && python -m gunicorn app:app --bind 0.0.0.0:$PORT --workers 4 --timeout 120"
restartPolicyType = "ON_FAILURE"
healthcheckPath = "/health"
healthcheckTimeout = 100 