version: '3'
services:
  whatsapp-service:
    build:
      target: development
    volumes:
      - ./whatsapp-service:/app:cached
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
      
  openai-service:
    build:
      target: development
    volumes:
      - ./openai-service:/app:cached
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1