version: '3.8'

services:
  whatsapp-service:
    build: ./whatsapp-service
    ports:
      - "8501:8501"
    env_file:
      - ./whatsapp-service/.env
    depends_on:
      - openai-service
      - db-service

  openai-service:
    build: ./openai-service
    ports:
      - "8502:8502"
    env_file:
      - ./openai-service/.env
    depends_on:
      - db-service

  db-service:
    build: ./db-service
    ports:
      - "8000:8000"
    env_file:
      - ./db-service/.env
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
