version: '3.8'

services:
  whatsapp-service:
    build: ./whatsapp-service
    env_file: ./whatsapp-service/.env
    ports:
      - "8501:8501"
    depends_on:
      - db-service
      - openai-service

  openai-service:
    build: ./openai-service
    env_file: ./openai-service/.env
    ports:
      - "8502:8502"
    depends_on:
      - db-service

  db-service:
    build: ./db-service
    env_file: ./db-service/.env
    ports:
      - "8000:8000"
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    volumes:
      - mongodb_data:/data/db
    command: [ "mongod", "--quiet", "--logpath", "/dev/null" ]
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongodb_data:
