version: '3.8'

services:
  whatsapp-service:
    build: ./whatsapp-service
    env_file: ./whatsapp-service/.env
    depends_on:
      - db-service
      - openai-service

  openai-service:
    build: ./openai-service
    env_file: ./openai-service/.env
    depends_on:
      - db-service

  db-service:
    build: ./db-service
    env_file: ./db-service/.env
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
