version: '3'
services:
  whatsapp-service:
    build: ./whatsapp-service
    env_file:
      - ./whatsapp-service/.env
    ports:
      - "8501:8501"
    depends_on:
      - openai-service
      - mongodb
    volumes:
      - ./utils:/app/utils
      - ./shared:/app/shared
    environment:
      - PORT=8501

  openai-service:
    build: ./openai-service
    env_file:
      - ./openai-service/.env
      - ./openai-service/.env.development
      - ./.env
    ports:
      - "8502:8502"
    depends_on:
      postgres:
        condition: service_healthy
      mongodb:
        condition: service_healthy
    volumes:
      - ./utils:/app/utils
      - ./shared:/app/shared
    environment:
      - PORT=8502

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5

  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    env_file:
      - ./.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  mongodb_data:
  postgres_data:
